languageCode: en-us
baseURL: "//chanin.tech/"
title: Ronny Munene
pagination.pageSize: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ChaninNantasenamat
  description: "This is the website of Ronny Munene, some of you may know me as the **The Alpha Male**."
  keywords: [Blog, Portfolio, Data Science]
  author: Ronny Munene
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Ronny Munene"
    icon: "images/coding.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hello World! \U0001F44B"
    subtitle: "This is the website of **Ronny Munene**, some of you may know me as the **The Alpha Male**."
    imageUrl: "images/profile picture.png" 
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Ronny Munene"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Hello World! \U0001F44B"
    Content: "This is the website of **Ronny Munene**, some of you may know me as the **The Alpha Male**."
  

  social:
    - name: medium
      url: "https://medium.com/@ronymunene360"
    - name: X
      url: "https://twitter.com/ronnymunene4"
    - name: linkedin
      url: "https://www.linkedin.com/in/ronny-munene/"
    - name: github
      url: "https://github.com/The-alpha-male"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/The-alpha-male/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link


  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 3
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2